spring:
    datasource:
        jmx-enabled: true
        username: postgres
        password: mysecretpassword
        url: jdbc:postgresql://192.168.1.36:5432/postgres
        driver-class-name: org.postgresql.Driver
        hikari:
          pool-name: car-pool
    jpa:
#      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop


